[package]
name = "rs3-bar-optimizer"
version = "0.1.0"
authors = [ "Ben Turner <7623873+ben-turner@users.noreply.github.com>" ]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
