name: CD
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install wasm-pack
        run: cargo install wasm-pack
      - name: Build
        run: wasm-pack build --target web
      - name: Package
        run: tar -czf gh_pages.tar.gz pkg index.html
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: gh_pages.tar.gz

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    
    environment:
      name: gh-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          preview: ${{ github.ref != 'refs/heads/main' }}
